### ISSUE TITLE
Bad naming

### ISSUE THREAD

**Issue by AlexRavodin** [yegorrusakovich/MovieRank_Flutter#1]
What does "aux" mean?

https://github.com/Demian23/MovieRank_Flutter/blame/9d16cefc3bfa845999c21c3baf43c943e9911d3e/lib/aux/data_source_decision_maker.dart#L1-L19

**Comment by yegorrusakovich** [comment]
> What does "aux" mean?
> 
> https://github.com/Demian23/MovieRank_Flutter/blame/9d16cefc3bfa845999c21c3baf43c943e9911d3e/lib/aux/data_source_decision_maker.dart#L1-L19

**Auxiliary**, directory with auxiliary modules
